server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RogerBariles/microservicios.git
          searchPaths: config-data
          username: RogerBariles
          password: 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
  security:
    user:
      name: root
      password: root