server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RogerBariles/microservicios.git
          searchPaths: config-data
          username: RogerBariles
          password: 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
  security:
    user:
      name: root
      password: root